name: validadores
description: Validadores para formulários PT-BR, validações como CPF,CNPJ,OBRIGATORIO,EMAIL,IGUAL,Valor Mínimo,Valor Máximo,Tamanho Mínimo,Tamanho Máximo.
version: 1.0.7
#author: Marcelo Tobias <marcelo.tobbias@gmail.com>
homepage: https://github.com/mtobbias/365apps-pack-validador

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8

